// <auto-generated />
using System;
using DesafioFullstack.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioFullstack.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DesafioFullstack.Entity.Attendance", b =>
                {
                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.Property<int>("CollaboratorId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopId", "CollaboratorId");

                    b.HasIndex("CollaboratorId");

                    b.ToTable("Attendance");

                    b.HasData(
                        new
                        {
                            WorkshopId = 1,
                            CollaboratorId = 1
                        },
                        new
                        {
                            WorkshopId = 1,
                            CollaboratorId = 2
                        },
                        new
                        {
                            WorkshopId = 1,
                            CollaboratorId = 3
                        },
                        new
                        {
                            WorkshopId = 1,
                            CollaboratorId = 4
                        },
                        new
                        {
                            WorkshopId = 2,
                            CollaboratorId = 1
                        },
                        new
                        {
                            WorkshopId = 2,
                            CollaboratorId = 2
                        },
                        new
                        {
                            WorkshopId = 2,
                            CollaboratorId = 3
                        },
                        new
                        {
                            WorkshopId = 2,
                            CollaboratorId = 4
                        },
                        new
                        {
                            WorkshopId = 3,
                            CollaboratorId = 1
                        },
                        new
                        {
                            WorkshopId = 3,
                            CollaboratorId = 2
                        },
                        new
                        {
                            WorkshopId = 3,
                            CollaboratorId = 3
                        },
                        new
                        {
                            WorkshopId = 3,
                            CollaboratorId = 4
                        },
                        new
                        {
                            WorkshopId = 4,
                            CollaboratorId = 1
                        },
                        new
                        {
                            WorkshopId = 4,
                            CollaboratorId = 2
                        },
                        new
                        {
                            WorkshopId = 4,
                            CollaboratorId = 3
                        },
                        new
                        {
                            WorkshopId = 4,
                            CollaboratorId = 4
                        });
                });

            modelBuilder.Entity("DesafioFullstack.Entity.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Collaborator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abfde"),
                            Name = "Colaborador 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abfd1"),
                            Name = "Colaborador 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abfd2"),
                            Name = "Colaborador 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abfd3"),
                            Name = "Colaborador 4"
                        });
                });

            modelBuilder.Entity("DesafioFullstack.Entity.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Workshop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Participe deste workshop prático e intensivo sobre tecnologia e aprenda com o especialista a dominar as técnicas e ferramentas essenciais para aplicar o conhecimento imediatamente.",
                            ExecutionDate = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abcde"),
                            Name = "Workshop 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descubra o potencial da IA. Neste evento, vamos explorar algoritmos de machine learning e criar um modelo preditivo do zero, sem necessidade de conhecimento prévio.",
                            ExecutionDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abcf1"),
                            Name = "Workshop de Inteligência Artificial"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aprenda a construir APIs robustas e escaláveis. Abordaremos desde os conceitos fundamentais de REST até a implementação de segurança com JWT e documentação com Swagger.",
                            ExecutionDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abcf2"),
                            Name = "APIs RESTful com .NET"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Focado em UI/UX, este workshop ensina a criar interfaces intuitivas e atraentes. Você aprenderá sobre prototipação, sistemas de design e testes de usabilidade.",
                            ExecutionDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Guid = new Guid("d3f1a2b4-5c6d-7e8f-9012-3456789abcf3"),
                            Name = "Design de Interfaces Modernas"
                        });
                });

            modelBuilder.Entity("DesafioFullstack.Entity.Attendance", b =>
                {
                    b.HasOne("DesafioFullstack.Entity.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioFullstack.Entity.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Workshop");
                });
#pragma warning restore 612, 618
        }
    }
}
